### ISSUE TITLE
Feature request: npm classnames like utility

### ISSUE THREAD

**Issue by claudiu-apetrei** [fulcrologic/fulcro-css#1]
Just a nice utility method to compose css classes and have conditional classname logic.
Would be pretty nice to have in fulcro-css even though it can be done in like 20lines of code. 
https://www.npmjs.com/package/classnames

There's already a port to cljs https://github.com/YurySolovyov/class-names-cljs

**Comment by awkay** [comment]
Please discuss feature requests on slack in #fulcro. When issues becomes a random dumping ground it gets out of hand quickly. If it comes up enough, work will get scheduled. Until then, it just creates clutter. If it is important, it'll continue to come up. If it isn't then it wasn't important. Either way it doesn't need to be tracked :)
