### ISSUE TITLE
Feature: Classnames shortened in production build 

### ISSUE THREAD

**Issue by claudiu-apetrei** [fulcrologic/fulcro-css#2]
Long explicit names are really nice for development mode.
But for production they will to add a lot to the bundle size.

Found a nice article about this topic: https://medium.freecodecamp.org/reducing-css-bundle-size-70-by-cutting-the-class-names-and-using-scope-isolation-625440de600b

Don't know if this is applicable to fulcro-css, would be cool if possible.

**Comment by awkay** [comment]
Please discuss these issues on #fulcro, and not in issues. Issues should only be for approved work in the work flow, or a bug report (ideally with a reproducible case).
